//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionCalculatorView.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectionCalculatorView.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to vote?.
        /// </summary>
        public static string AreYouVote {
            get {
                return ResourceManager.GetString("AreYouVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for candidates.
        /// </summary>
        public static string CandidatesResults {
            get {
                return ResourceManager.GetString("CandidatesResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot login because you haven&apos;t eighteen years..
        /// </summary>
        public static string HaveNotEighteenYears {
            get {
                return ResourceManager.GetString("HaveNotEighteenYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PESEL.
        /// </summary>
        public static string InvalidPESEL {
            get {
                return ResourceManager.GetString("InvalidPESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of invalid votes.
        /// </summary>
        public static string NumberOfInvalidVotes {
            get {
                return ResourceManager.GetString("NumberOfInvalidVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of valid votes.
        /// </summary>
        public static string NumberOfValidVotes {
            get {
                return ResourceManager.GetString("NumberOfValidVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of votes.
        /// </summary>
        public static string NumberOfVotes {
            get {
                return ResourceManager.GetString("NumberOfVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of votes without vote right.
        /// </summary>
        public static string NumberOfVotesWithoutRight {
            get {
                return ResourceManager.GetString("NumberOfVotesWithoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for parties.
        /// </summary>
        public static string PartiesResults {
            get {
                return ResourceManager.GetString("PartiesResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL.
        /// </summary>
        public static string PESEL {
            get {
                return ResourceManager.GetString("PESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string RequiredFirstName {
            get {
                return ResourceManager.GetString("RequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string RequiredLastName {
            get {
                return ResourceManager.GetString("RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot login because you have already voted..
        /// </summary>
        public static string YouHaveAlreadyVoted {
            get {
                return ResourceManager.GetString("YouHaveAlreadyVoted", resourceCulture);
            }
        }
    }
}
